### PR TITLE
Remove Text helpers

### PR DESCRIPTION
**Pull request by tysongach**
Our Text component is the only component which offers special helpers for each variant, even though many components have variants. To keep things consistent, let’s remove these special helpers.

```diff
-<%= anchor_text_body_base t(".text") %>
+<%= anchor_text t(".text"), variant: :body_base %>
```

### CODE REVIEW

**Review by Simonpedro — APPROVED** [review]
I think this makes sense, thank you!

**Review by tute — APPROVED** [review]

**Comment by MatheusRich** [comment]
Let's not forget to add that this is a breaking change on our release notes.

**Review by arzezak — APPROVED** [review]

**Comment by arzezak** [comment]
@tysongach Is there a reason we didn't get to merge this one? Getting rid of the iteration should solve the TextComponent error engineers have seen in BuoyRails.

**Comment by tysongach** [comment]
@arzezak Not really - thanks for the nudge!

**Pull request merged**
