### PR TITLE
Don't call model_name without a form object

### PR DESCRIPTION
**Pull request by arzezak**

### CODE REVIEW

**Comment by tysongach** [comment]
Does this fix a bug and, if so, can you expand on that?

**Comment by arzezak** [comment]
> Does this fix a bug and, if so, can you expand on that?

I just added a spec that fails without these changes. Without a model to call `#model_name` on we were failing to render successfully.

**Comment by arzezak** [comment]
@tysongach, Good to merge?

**Review by tysongach — APPROVED** [review]
Yep!

**Pull request merged**
