### PR TITLE
add form_for view helper

### PR DESCRIPTION
**Pull request by ryanong**

### CODE REVIEW

**Comment by ryanong** [comment]
not any really, form_for is more commonly used and sets scope automatically

**Comment by tute** [comment]
As I understand `form_with` is the new default that unites both `form_for` and `form_tag` helpers. I think we'd want to move over to `form_with`, which is very similar to previous usages anyway.

**Comment by ryanong** [comment]
Is it? neat didn't know that, I'm behind on rails helpers best practices

**Comment by MatheusRich** [comment]
For context: `form_for` and `form_tag` [are soft deprecated](https://guides.rubyonrails.org/form_helpers.html#using-form-tag-and-form-for).

**Comment by calebhearth** [comment]
Was just going to point that out - form_with is the new suggested API.

**Pull request closed without merging**
