### PR TITLE
Add Table component

### PR DESCRIPTION
**Pull request by tysongach**
https://app.asana.com/0/1203925238636526/1204836229892913/f

Screenshot 2023-06-29 at 12 31 48

### CODE REVIEW

**Comment by tute** [comment]
Hey @tysongach! I was going to migrate the questionnaires index page from React to Rails, but I'll need the work in this PR (see https://app.asana.com/0/1203925124186299/1205227290858938). Will you work on this soon? Can I help you with it? TY!

**Comment by tysongach** [comment]
@tute Hi Tute! I’m going to be working on it this week - I had to pause my efforts for a bit as I worked on extracting this system into its own repo and packages. Now back to this Table!

The current shape of this PR is a _very_ basic component, which I don’t think will get very far. What kinds of features do you need with tables?

**Comment by tute** [comment]
I'll also need to go granular with dataid attributes (on rows, potentially on cells). I've seen an API simple_form has for collections to allow such granular configuration as a third parameter (label, value, attributes).

**Comment by tysongach** [comment]
Closing in favor of #33

**Pull request closed without merging**
