### PR TITLE
fix: FormBuilder#check_box data attributes

### PR DESCRIPTION
**Pull request by elias19r**
Use `deep_merge` instead of `merge` to avoid overriding all data
attributes passed in the `options` argument.

### CODE REVIEW

**Review by arzezak — COMMENTED** [review]
Looks good. What do you think of adding a spec? Thank you.

**Comment by elias19r** [comment]
> Looks good. What do you think of adding a spec? Thank you.

That's a good idea! Updated in https://github.com/BuoySoftware/anchor_view_components/pull/180/commits/a857661bfc775763f08575c84b46d09669c59041

**Review by tysongach — COMMENTED** [review]
Lovely! Mind running `yarn changeset` to add a [changeset entry](https://github.com/BuoySoftware/anchor_view_components/blob/main/RELEASING.md)? Then this should be good to go.

**Review by arzezak — APPROVED** [review]
Great!

**Review by tysongach — APPROVED** [review]

**Pull request merged**
