### PR TITLE
Add specs

### PR DESCRIPTION
**Pull request by tysongach**

### CODE REVIEW

**Comment by dgalarza** [comment]
@tysongach if you'd like I can help take this over and get specs working.

**Comment by tysongach** [comment]
@dgalarza That would be super helpful - thanks!

**Review by tute — APPROVED** [review]
I didn't see output about what or how many specs it ran. How can I check for that? Code looks good to me but would like to find that!

**Comment by dgalarza** [comment]
@tute good question! I've added the `progress` formatter as well so we can have both the spec details in the worker output and the errors reported in the pull request. Note, it looks like we get blank output in Infirmary as well. We may want to update that.

**Pull request merged**
