### PR TITLE
Support custom row styling in TableComponent

### PR DESCRIPTION
**Pull request by dgalarza**
https://app.asana.com/0/1203925238636526/1205732047850445/f

image

### CODE REVIEW

**Review by Simonpedro — COMMENTED** [review]
Would it be ok for models to be responsible or be aware of UI/style affairs? As an alternative, to avoid referencing tailwind classes in a model, what you think about adding a new lambda attribute as an indirection layer instead?

```rb
anchor_table(row_classes: ->(model) { ["text-critical"] if model.id.even? }, **other_params)
```

**Comment by dgalarza** [comment]
@Simonpedro good question. I envisioned mapping the models with another class like a presenter to handle the view logic. I was also curious if it was a bad idea to have a template-less view component. So instead of using a presenter you wrapped the individual objects for the table in the view component which might hold the logic like the `StyledMockData`.

That being said, what you've suggested eliminates the need for another object or class which I kind of like.

**Comment by dgalarza** [comment]
@Simonpedro updated!

**Comment by Simonpedro** [comment]
@dgalarza I see, we add these methods in a presenter, not in the model. Nonetheless, you'd have to explicitly wrap all objects with this new presenter and call `.map` on the collection, which could potentially be a scope, which in turns resolve any pending query; I'm not sure this approach plays well with the pagination functionality, which expects a non-resolved scope.

Apart from this point, I also like the lambda approach, if you search for `.call` in the component you'd noticed we've been using the pattern a couple of times.

**Review by Simonpedro — APPROVED** [review]
Sorry I had commented before the update ha, thank you!

**Pull request merged**
